### ISSUE TITLE
Separate date and time from datetime

### ISSUE THREAD

**Issue by heiders** [Edo78/obsidian-koreader-sync#21]
I'm an avid user of daily notes in Obsidian, which all have the title as [[yyyy-mm-dd]]. If the date in the KOReader notes is listed separately from the time in the frontmatter, I could use dataview to create an automatic "Books I read today" table in my daily note with: 

```dataview
table without id koreader-sync.data.title AS Title
where koreader-sync.data.datetime = date(today)
```

Also, I would be able to use the custom template to include a link to my daily note.

**Comment by Edo78** [comment]
Right now I have no use for `datetime`, in KOReader is a string and I just take it "as is" but I should be able to easily parse is and put the single pieces in FM
Eg. (just on top of my head)
```YAML
  exploded_datetime:
    - year: 2022
    - month: 01
    - month_name: January
    - day: 26
    - hour: 21
    - hour_12: 9
    - am_pm: PM
    - minute: 46
    - second: 37
```
So anyone can play with the various pieces.
What do you think? Can this solve your issue?
